---
title: "Plotly"
---

### Problem 2


```{r}
library(tidyverse)
library(plotly)
library(dplyr)
library(p8105.datasets)
```

Loading data

```{r}
data("instacart")

instacart = 
  instacart %>% 
  as_tibble()

instacart = 
  instacart %>% 
  head(600) |>
  select(add_to_cart_order, reordered, user_id, order_number, order_hour_of_day, days_since_prior_order, product_name, aisle_id, product_id, aisle, department)
  
```

### Making a Boxplot

```{r}

instacart |> 
  plot_ly(y = ~order_hour_of_day, x = ~department, color = ~department, type = "box", colors = "viridis")
  
```

This plot shows the relationship between the hour of day when an item is ordered and the department they come from

### Making a Scatterplot

```{r}
instacart |>
  mutate(text_label = str_c("Product:", product_name)) |>
  plot_ly(
    x = ~product_id, y = ~add_to_cart_order, type = "scatter", mode = "markers",
   color = ~department, alpha = 0.5, colors = "viridis")
  
```

This plot shows `product_id` against `add_to_cart_order`

### Making a Barchart

```{r}
instacart |> 
  count(aisle) |>
  mutate(aisle = fct_reorder(aisle, n)) |> 
  plot_ly(x = ~aisle, y = ~n, color = ~aisle, type = "bar", colors =  "viridis")
```

This plot shows the items in each aisle compared to the amount of items in each aisle