---
title: "Resume"
---

# Education 

**New York University, College of Arts and Science, New York, NY;  Bachelor of Arts, Psychology (Pre-Medical)               May 2023**

**Columbia University, Mailman School of Public Health, New York, NY; Masters of Science, Epidemiology 	            May 2025**


# Experience

**Student Intern, NYU Langone Health Care Opportunity Program, New York, NY**			
*Shadowed physicians within the neurology department at NYU Langone under the supervision of Dr. Abou-Fayssal*
*Actively participated in lectures and group discussions regarding medical ethics from various healthcare professionals*

**Student Researcher, NYU Polygeia, New York, NY**			

*Conduct a literature review regarding traumatic brain injury from intimate partner violence among women veterans*
*Read through 40+ published research papers to collect information and compile a report with other researchers*

**Zoom Assistant, NYU IT, New York, NY**	

*Help bridge the gap created by virtual and online learning through providing technical support, such as communicating with students and professors and performing Zoom functions*

**Corps Member, Jumpstart, New York, NY**                                       

*Support emotional development and educational skills of children 3-5 years old in low-income areas through storytelling, vocabulary, and reinforcing activities*
*Develop and execute lesson plans; collaborate with colleagues to create a comforting space for children*

**Volunteer, Sibs Place (Affiliate of Mount Sinai) , Hewlett, NY**			         

*Used prevention theory methods to assist children in coping with their feelings of having a family member diagnosed with a chronic illness through problem solving and stress reducing activities*
*Supported children in developing meaningful relationships and validating their feelings by connecting them with others who have shared experiences*
 
**Student Researcher, Science Research, East Meadow, NY**		                  	

*Conducted research experiments regarding environmental health using D-Limonene to degrade polystyrene in landfills and reduce the release of chemicals into the atmosphere; Competed at NYSSEF and LISC*


# Leadership Activities 

**Resident Assistant, NYU Residential Life, New York, NY**

*Develop and foster a positive community and living environment for 44 residents by planning and hosting programs, aiding with roommate conflicts, and counseling residents regarding various personal and academic issues*
*Implement and enforce Residential Policies and administrative duties such as managing mailroom and filing incident reports*

**President, NYU Class Activities Board, New York, NY**				                   

*Oversee Executive Board to develop programs for over 7000 undergraduate students in our year, represent the Class of 2023 in Student Government by having a voting seat on President’s Council; provide support to students through programming*
*Schedule and participate in weekly meetings where we discuss details of event planning, budgeting, and leadership updates*

**Student Leader, NYU Welcome, New York, NY	*		       	                          
*Collaborate with administrators to develop and design 300+ events for the 28,000+ NYU undergraduate student population by creating event plans and communicating with vendors; served multiple leadership roles within the organization*
*Support transition of First Year and Transfer students through intentional programming and consistent communication*

**Volunteer, Crisis Text Line, New York, NY**					                                             
*Counsel texters dealing with depression, anxiety, suicidal thoughts to bring them from an anxious to a calm state*

**PR & Marketing Manager, NYU Share Meals, New York, NY**	

*Collaborate with officers to create informative events regarding food insecurity, and provide resources to NYU students who are food insecure through various social media platforms and newsletters*
